name: Build GPU ROCK

on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "amd64"
        required: true
      export-test-image:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ${{ inputs.arch == 'amd64' && 'ubuntu-22.04' || 'ubuntu-22.04-arm' }}
    timeout-minutes: 60
    steps:
      - name: Disk cleanup
        shell: bash
        run: |
          sudo rm -rf \
            /opt/google \
            /opt/hostedtoolcache \
            /opt/microsoft/powershell \
            /opt/microsoft/msedge \
            "$AGENT_TOOLSDIRECTORY" \
            /usr/lib/firefox \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/gradle* \
            /usr/share/miniconda \
            /usr/share/sbt \
            /usr/share/swift \
            /home/linuxbrew
          pipx uninstall-all
          printf '\nDisk usage\n'
          df --human-readable

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.21/stable

      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic

      - name: Build image (GPU)
        run: sudo make build FLAVOUR=gpu

      - name: Get Artifact Name
        id: artifact
        run: |
          GPU_ARTIFACT=$(make help FLAVOUR=gpu | grep 'Artifact: ')
          echo "gpu_artifact_name=${GPU_ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT

      - name: Change artifact permissions
        run: sudo chmod a+r  ${{ steps.artifact.outputs.gpu_artifact_name }}

      - name: Upload locally built artifact
        uses: actions/upload-artifact@v6
        with:
          name: charmed-spark-gpu-${{ inputs.arch }}
          path: |
            ${{ steps.artifact.outputs.gpu_artifact_name }}

      - name: Export test image
        if: ${{ inputs.export-test-image }}
        run: |
          export SPARK_VERSION=$(yq .version images/charmed-spark-gpu/rockcraft.yaml)
          export GPU_VERSION=$(yq .flavours.gpu.version images/metadata.yaml)

          sudo snap install regclient
          sudo docker run -d -p 5000:5000 --restart always --name local-registry registry:latest
          rockcraft.skopeo --insecure-policy copy \
            oci-archive:${{ steps.artifact.outputs.gpu_artifact_name }} \
            "docker://localhost:5000/ghcr.io/canonical/test-charmed-spark-gpu:${SPARK_VERSION}-${GPU_VERSION}" \
            --dest-tls-verify=false
          regctl image export \
            "localhost:5000/ghcr.io/canonical/test-charmed-spark-gpu:${SPARK_VERSION}-${GPU_VERSION}" \
            --name "ghcr.io/canonical/test-charmed-spark-gpu:${SPARK_VERSION}-${GPU_VERSION}" \
            --host reg=localhost:5000,tls=disabled >test_image.tar

      - name: Upload test artifact
        if: ${{ inputs.export-test-image }}
        uses: actions/upload-artifact@v6
        with:
          name: charmed-spark-gpu-test-${{ inputs.arch }}
          path: test_image.tar
