name: Build GPU ROCK

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install yamllint
        run: python3 -m pip install yamllint
      - name: YAML Lint
        run:  |
          yamllint -d "{extends: relaxed, rules: {line-length: {max: 250}}}" \
            --no-warnings images/charmed-spark-gpu/rockcraft.yaml

  checks:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic --edge

      - name: Verify default Spark image
        id: verify-default-image
        run: |
          echo "Extracting image from spark-defaults.conf"
          DEFAULT_IMAGE_LINE=$(grep -E '^spark.kubernetes.container.image=' images/charmed-spark/conf/spark-defaults.conf || true)
          IMAGE=${DEFAULT_IMAGE_LINE#*=}
          echo "Default Spark Image: ${IMAGE}"

          echo "Inspecting image with rockcraft.skopeo"
          if ! rockcraft.skopeo inspect "docker://${IMAGE}"; then
            echo "Image ${IMAGE} not found or inspect failed" >&2
            exit 1
          fi

          echo "Cross-checking with rockcraft.yaml"
          VERSION=$(yq .version images/charmed-spark/rockcraft.yaml)
          MAJOR_MINOR=$(echo "${VERSION}" | awk -F. '{print $1"."$2}')
          echo "rockcraft version: ${VERSION} (major_minor=${MAJOR_MINOR})"

          if ! echo "${IMAGE}" | grep -q "${MAJOR_MINOR}"; then
            echo "Image tag does not contain version prefix ${MAJOR_MINOR}" >&2
            exit 1
          fi

          echo "Verification of Spark default image passed."
      
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs:
      - lint
      - checks
    steps:
      - name: Disk cleanup
        shell: bash
        run: |
          sudo rm -rf \
            /opt/google \
            /opt/hostedtoolcache \
            /opt/microsoft/powershell \
            /opt/microsoft/msedge \
            "$AGENT_TOOLSDIRECTORY" \
            /usr/lib/firefox \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/gradle* \
            /usr/share/miniconda \
            /usr/share/sbt \
            /usr/share/swift \
            /home/linuxbrew
          pipx uninstall-all
          printf '\nDisk usage\n'
          df --human-readable

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.21/stable

      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic --edge

      - name: Build image (GPU)
        run: sudo make build FLAVOUR=gpu

      - name: Get Artifact Name
        id: artifact
        run: |
          GPU_ARTIFACT=$(make help FLAVOUR=gpu | grep 'Artifact: ')
          echo "gpu_artifact_name=${GPU_ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT

      - name: Change artifact permissions
        run: sudo chmod a+r  ${{ steps.artifact.outputs.gpu_artifact_name }}

      - name: Upload locally built artifact
        uses: actions/upload-artifact@v4
        with:
          name: charmed-spark-gpu
          path: |
            ${{ steps.artifact.outputs.gpu_artifact_name }}

