name: Build ROCK

on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: ""

jobs:
  build:
    strategy:
      matrix:
        system:
          - os: ubuntu-22.04
            arch: amd64
          - os: ubuntu-22.04-arm
            arch: arm64
    runs-on: ${{ matrix.system.os }}
    timeout-minutes: 30
    steps:
      - name: Disk cleanup
        shell: bash
        run: |
          sudo rm -rf \
            /opt/google \
            /opt/hostedtoolcache \
            /opt/microsoft/powershell \
            /opt/microsoft/msedge \
            "$AGENT_TOOLSDIRECTORY" \
            /usr/lib/firefox \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/gradle* \
            /usr/share/miniconda \
            /usr/share/sbt \
            /usr/share/swift \
            /home/linuxbrew
          pipx uninstall-all
          printf '\nDisk usage\n'
          df --human-readable

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.21/stable

      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic --edge

      - name: Build image
        run: sudo make build

      - name: Build image (Jupyter)
        run: sudo make build FLAVOUR=jupyter

      - name: Build image (Kyuubi)
        run: sudo make build FLAVOUR=kyuubi

      - name: Get Artifact Name
        id: artifact
        run: |
          BASE_ARTIFACT=$(make help | grep 'Artifact: ')
          echo "base_artifact_name=${BASE_ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT
          JUPYTER_ARTIFACT=$(make help FLAVOUR=jupyter | grep 'Artifact: ')
          echo "jupyter_artifact_name=${JUPYTER_ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT
          KYUUBI_ARTIFACT=$(make help FLAVOUR=kyuubi | grep 'Artifact: ')
          echo "kyuubi_artifact_name=${KYUUBI_ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT

      - name: Change artifact permissions
        run: sudo chmod a+r  ${{ steps.artifact.outputs.base_artifact_name }} ${{ steps.artifact.outputs.jupyter_artifact_name }} ${{ steps.artifact.outputs.kyuubi_artifact_name }}

      - name: Upload locally built artifacts
        uses: actions/upload-artifact@v6
        with:
          name: charmed-spark-${{ matrix.system.arch }}
          path: |
            ${{ steps.artifact.outputs.base_artifact_name }}
            ${{ steps.artifact.outputs.jupyter_artifact_name }}
            ${{ steps.artifact.outputs.kyuubi_artifact_name }}
