# Copyright 2026  Canonical Ltd.
# See LICENSE file for licensing details.
name: CI pipeline

on:
  pull_request:

jobs:
  integration:
    uses: ./.github/workflows/integration.yaml

  integration-gpu-amd:
    uses: ./.github/workflows/integration-gpu.yaml
    with:
      arch: "amd64"

  integration-gpu-arm:
    uses: ./.github/workflows/integration-gpu.yaml
    with:
      arch: "arm64"
