name: Spark Image Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build-rock:
    uses: ./.github/workflows/build.yaml
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    needs: build-rock
    strategy:
      matrix:
        env: [integration]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup LXD
        uses: canonical/setup-lxd@main
      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic --edge
      - name: Install microk8s
        run: bash tests/integration/setup-microk8s.sh
      - name: Configure microk8s
        run: sg microk8s tests/integration/config-microk8s.sh
      - name: Install tox
        run: python3 -m pip install tox
      - name: Run Integration tests
        run: sg microk8s -c "tox -e ${{ matrix.env }}"