name: Spark Image Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        run: |
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker

      - name: Install skopeo
        run: |
          sudo apt-get install uidmap
          sudo snap install --devmode --channel edge skopeo

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Build ROCK
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - name: Build Images
        run: make integration-tests PREFIX=test- REPOSITORY=ghcr.io/canonical/

      - name: Upload built OCI tarball artifacts
        uses: actions/upload-artifact@v3
        with:
          name: charmed-spark
          path:  .make_cache/**/*.tar

