name: Spark Image Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  build-rock:
    uses: ./.github/workflows/build.yaml
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    needs: build-rock
    strategy:
      matrix:
        env: [integration]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Artifact Name
        id: artifact
        run: |
          ARTIFACT=$(make help | grep 'Artifact: ')
          echo "name=${ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT

      - name: Install and configure microk8s
        run: |
          make microk8s

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: charmed-spark
          path: charmed-spark

      - name: Run tests
        run: |
          # Unpack Artifact
          mv charmed-spark/${{ steps.artifact.outputs.name }} .
          rmdir charmed-spark

          # Import artifact into docker with new tag
          sudo make import TARGET=docker REPOSITORY=ghcr.io/canonical/ PREFIX=test- \
            -o ${{ steps.artifact.outputs.name }} 

          # Import artifact into microk8s to be used in integration tests
          sudo make import TARGET=microk8s PREFIX=test- REPOSITORY=ghcr.io/canonical/ \
            -o $(find .make_cache -name "*.tag")
          
          sg microk8s -c "make tests"

      - name: Run tests (Jupyter)
        run: |
          # Import artifact into docker with new tag
          sudo make import \
            FLAVOUR=jupyter TARGET=microk8s \
            TAG=$(yq .version rockcraft.yaml) \
            REPOSITORY=ghcr.io/canonical/ PREFIX=test- \
            -o $(find .make_cache -name "*.tag")

          sg microk8s -c "make tests FLAVOUR=jupyter"
