name: Spark Image Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-rock:
    uses: ./.github/workflows/build.yaml
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    needs: build-rock
    strategy:
      matrix:
        env: [integration]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: charmed-spark-rock
      - name: ls
        run: ls; ls charmed-spark-rock;