name: GPU integration CI pipeline

on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "amd64"
        required: true

jobs:
  build-rock:
    uses: ./.github/workflows/build_gpu.yaml
    with:
      arch: ${{ inputs.arch }}

  start-runner:
    name: Start self-hosted EC2 runner
    needs: [build-rock]
    runs-on: ubuntu-22.04
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2.4.1
        with:
          mode: start
          github-token: ${{ secrets.WELPAOLO_GITHUB_TOKEN }}
          ec2-image-id: ${{ inputs.arch == 'amd64' && vars.AWS_EC2_IMAGE_ID_AMD || vars.AWS_EC2_IMAGE_ID_ARM }}
          ec2-instance-type: ${{ inputs.arch == 'amd64' && vars.AWS_EC2_INSTANCE_TYPE_AMD || vars.AWS_EC2_INSTANCE_TYPE_ARM }}
          subnet-id: ${{ vars.AWS_DEFAULT_SUBNET_ID }}
          security-group-id: ${{ vars.AWS_SECURITY_GROUP_ID }}

  integration-tests:
    name: Run integration tests
    needs: [start-runner]
    runs-on: ${{ needs.start-runner.outputs.label }}
    strategy:
      matrix:
        k8s_version:
          - "1.32"
          - "1.34"
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup environment
        run: |
          sudo systemctl disable --now unattended-upgrades.service
          sudo apt autoremove unattended-upgrades -y
          sudo apt update
          sudo apt install build-essential -yqq
          
          sudo snap install yq
          sudo snap install concierge --classic

          # Set the K8s version
          cp concierge.yaml /var/snap/yq/common/.
          yq -i e '.providers.k8s.channel = "${{ matrix.k8s_version }}-classic/stable"' /var/snap/yq/common/concierge.yaml
          cp /var/snap/yq/common/concierge.yaml . 
          
          cat concierge.yaml
          
          sudo concierge prepare

          mkdir -p /home/ubuntu/.kube
          sudo chown -f -R ubuntu /home/ubuntu/.kube
          sudo k8s config | tee /home/ubuntu/.kube/config
          
          sudo k8s kubectl version

      - name: Deploy gpu operator
        timeout-minutes: 10
        env:
          KUBECONFIG: "/home/ubuntu/.kube/config"
        run: |
          helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
          helm repo update
          helm install --generate-name -n gpu-operator-resources --create-namespace nvidia/gpu-operator
          # Wait for gpu operator components to be ready
          while ! sudo kubectl logs -n gpu-operator-resources -l app=nvidia-operator-validator | grep "all validations are successful"
          do
              echo "--------------------------------------------------------------------------------------------------------------------"
              echo "waiting for validations"
              sudo kubectl get pods -n gpu-operator-resources
              sleep 60
              echo "--------------------------------------------------------------------------------------------------------------------"
          done

      - name: Setup object storage
        run: |
          sudo microceph cluster bootstrap
          sudo microceph disk add loop,1G,3
          sudo microceph enable rgw
          sudo microceph.radosgw-admin user create --uid test --display-name test --access-key=foo --secret-key=bar
          aws configure set aws_access_key_id foo
          aws configure set aws_secret_access_key bar
          aws configure set endpoint_url "http://$(ip -4 -j route get 2.2.2.2 | yq -r '.[] | .prefsrc'):80"
          aws s3 ls

      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: charmed-spark-gpu-${{ inputs.arch }}
          path: charmed-spark

      - name: Load test image
        run: |
          sudo mkdir /var/snap/k8s/common/images
          sudo cp charmed-spark/*.tar /var/snap/k8s/common/images/
          sudo snap restart k8s.containerd
          sleep 30
          if [ -z "$(sudo /snap/k8s/current/bin/ctr --address /run/containerd/containerd.sock --namespace k8s.io images list -q | grep test-charmed-spark)" ]; then
            sleep 30
            if [ -z "$(sudo /snap/k8s/current/bin/ctr --address /run/containerd/containerd.sock --namespace k8s.io images list -q | grep test-charmed-spark)" ]; then
              echo "Test image not loaded"
              exit 1
            fi
          fi

      - name: Run integration tests on GPU
        run: |
          echo "Start test..."
          export S3_ACCESS_KEY=foo
          export S3_SECRET_KEY=bar
          export S3_ENDPOINT="http://$(ip -4 -j route get 2.2.2.2 | yq -r '.[] | .prefsrc'):80"
          /bin/bash ./tests/integration/integration-tests-gpu.sh
          echo "End of the test :)"
        env:
          KUBECONFIG: "/home/ubuntu/.kube/config"
          USER: "ubuntu"

      - name: Cleanup
        if: ${{ always() }}
        run: |
          sudo snap remove k8s --purge
          sudo snap remove microceph --purge
          
          sudo apt-get remove -y docker.io containerd
          sudo rm -rf /run/containerd


  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - integration-tests
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2.4.1
        with:
          mode: stop
          github-token: ${{ secrets.WELPAOLO_GITHUB_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
