# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to GHCR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "3.4/edge"
      - "3.5/edge"

jobs:
  build-rocks:
    uses: ./.github/workflows/build.yaml

  build-rock-gpu-amd:
    uses: ./.github/workflows/build_gpu.yaml
    with:
      arch: amd64

  build-rock-gpu-arm:
    uses: ./.github/workflows/build_gpu.yaml
    with:
      arch: arm64

  trivy:
    needs: build-rocks
    uses: ./.github/workflows/trivy.yaml

  release-images:
    name: Release images
    runs-on: ubuntu-24.04
    needs: [build-rocks, build-rock-gpu-amd, build-rock-gpu-arm]
    permissions:
      packages: write # Needed to publish to GitHub Container Registry
      contents: write # Needed to create git tags
    steps:
      - name: Disk cleanup
        run: |
          sudo rm -rf \
            /opt/google \
            /opt/hostedtoolcache \
            /opt/microsoft/powershell \
            /opt/microsoft/msedge \
            "$AGENT_TOOLSDIRECTORY" \
            /usr/lib/firefox \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/gradle* \
            /usr/share/miniconda \
            /usr/share/sbt \
            /usr/share/swift \
            /home/linuxbrew
          pipx uninstall-all
          printf '\nDisk usage\n'
          df --human-readable

      - name: Install tooling
        # The release-rock command is installed here from the shared workflows
        # using pipx
        run: |
          sudo snap install rockcraft --channel latest/edge --classic
          sudo snap alias rockcraft.skopeo skopeo
          sudo snap install yq
          pipx install git+https://github.com/canonical/data-platform-workflows#subdirectory=_cli

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: unused # Required input—but not used
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: charmed-spark-*

      - name: Reorganize and convert images
        # The release-rock command requires a flavor's images to be in the same folder,
        # using the compressed oci-archive format (so we need to convert what we have) and
        # it needs a rockcraft.yaml file to read the name, base & version from
        run: |
          mkdir -p to_convert \
            to_export/charmed-spark \
            to_export/charmed-spark-kyuubi \
            to_export/charmed-spark-jupyterlab \
            to_export/charmed-spark-gpu
          mv charmed-spark-*/* to_convert

          for file in to_convert/*; do
              echo "Processing $file"
              rockcraft.skopeo --insecure-policy copy "docker-archive:${file}" "oci-archive:${file%.*}.rock"
          done
          mv to_convert/charmed-spark-kyuubi*.rock to_export/charmed-spark-kyuubi/
          mv to_convert/charmed-spark-jupyterlab*.rock to_export/charmed-spark-jupyterlab/
          mv to_convert/charmed-spark-gpu*.rock to_export/charmed-spark-gpu/
          mv to_convert/charmed-spark*.rock to_export/charmed-spark/

          cp images/charmed-spark/rockcraft.yaml to_export/charmed-spark/
          cp images/charmed-spark-gpu/rockcraft.yaml to_export/charmed-spark-gpu/
          yq '. | pick(["name", "version", "base"]) | .name |= "charmed-spark-kyuubi"' images/charmed-spark/rockcraft.yaml > to_export/charmed-spark-kyuubi/rockcraft.yaml
          yq '. | pick(["name", "version", "base"]) | .name |= "charmed-spark-jupyterlab"' images/charmed-spark/rockcraft.yaml > to_export/charmed-spark-jupyterlab/rockcraft.yaml

      - name: Upload & release rocks
        id: release
        run: |
          release-rock --directory=to_export/charmed-spark/ --create-tags=true
          release-rock --directory=to_export/charmed-spark-kyuubi/ --create-tags=true
          release-rock --directory=to_export/charmed-spark-jupyterlab/ --create-tags=true
          release-rock --directory=to_export/charmed-spark-gpu/ --create-tags=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-tag OCI resources
        id: retag
        run: |
          FULL_SPARK_VERSION=$(yq '.version' images/charmed-spark/rockcraft.yaml)
          BASE=$(yq '(.base|split("@"))[1]' images/charmed-spark/rockcraft.yaml)
          ORIGINAL_TAG="${FULL_SPARK_VERSION}-${BASE}_edge"
          MAJOR_MINOR_VERSION=$(echo $FULL_SPARK_VERSION | sed -n "s/\(^[0-9]*\.[0-9]*\).*/\1/p")
          MAJOR_MINOR_TAG="${MAJOR_MINOR_VERSION}-${BASE}_edge"

          echo "Re-tagging charmed-spark"
          skopeo copy --insecure-policy \
            "docker://ghcr.io/canonical/charmed-spark:${ORIGINAL_TAG}" \
            "docker://ghcr.io/canonical/charmed-spark:${MAJOR_MINOR_TAG}" --all

          echo "Re-tagging charmed-spark-kyuubi"
          FULL_KYUUBI_TAG="${FULL_SPARK_VERSION}-$(yq '.flavours.kyuubi.version' images/metadata.yaml)-${BASE}_edge"
          skopeo copy --insecure-policy \
            "docker://ghcr.io/canonical/charmed-spark-kyuubi:${ORIGINAL_TAG}"\
            "docker://ghcr.io/canonical/charmed-spark-kyuubi:${MAJOR_MINOR_TAG}" --all
          skopeo copy --insecure-policy \
            "docker://ghcr.io/canonical/charmed-spark-kyuubi:${ORIGINAL_TAG}"\
            "docker://ghcr.io/canonical/charmed-spark-kyuubi:${FULL_KYUUBI_TAG}" --all

          echo "TODO: Re-tagging charmed-spark-jupyterlab"

          echo "Re-tagging charmed-spark-gpu"
          FULL_GPU_TAG="${FULL_SPARK_VERSION}-$(yq '.flavours.gpu.version' images/metadata.yaml)-${BASE}_edge"
          skopeo copy --insecure-policy \
            "docker://ghcr.io/canonical/charmed-spark-gpu:${ORIGINAL_TAG}"\
            "docker://ghcr.io/canonical/charmed-spark-gpu:${MAJOR_MINOR_TAG}" --all
          skopeo copy --insecure-policy \
            "docker://ghcr.io/canonical/charmed-spark-gpu:${ORIGINAL_TAG}"\
            "docker://ghcr.io/canonical/charmed-spark-gpu:${FULL_GPU_TAG}" --all
