name: trivy
on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: ""
      submit_dependency_graph:
        description: "Submit SBOM to GitHub Dependency Graph"
        required: false
        type: boolean
        default: false

jobs:
  build:
    if: ${{ inputs.branch }}
    uses: ./.github/workflows/build.yaml
    with:
      branch: ${{ inputs.branch }}

  scan:
    name: Trivy scan and sbom generation
    needs: build
    if: always()
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour:
          - charmed-spark
          - charmed-spark-kyuubi
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ inputs.branch }}

      - name: Install rockcraft (for skopeo)
        run: |
          sudo snap install rockcraft --classic

      - name: Cache Trivy DB
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: .cache/trivy
          key: ${{ runner.os }}-trivy-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-trivy-

      - name: Get Artifact Name
        id: artifact
        run: |
          FLAVOUR=${{ matrix.flavour }}
          BASE_ARTIFACT=$(make help | grep 'Artifact: ' | sed "s/charmed-spark/$FLAVOUR/g" | sed "s/amd64/${{ matrix.arch }}/g")
          echo "base_artifact_name=${BASE_ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: charmed-spark-${{ matrix.arch }}
          path: charmed-spark

      - name: Import locally
        run: |
          # Unpack artifact
          mv charmed-spark/${{ steps.artifact.outputs.base_artifact_name }} .
          sudo rockcraft.skopeo --insecure-policy copy \
            docker-archive:${{ steps.artifact.outputs.base_artifact_name }} \
            docker-daemon:trivy/${{ matrix.flavour }}-${{ matrix.arch }}:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8
        # v0.36.0
        with:
          image-ref: "trivy/${{ matrix.flavour }}-${{ matrix.arch }}:${{ github.sha }}"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "MEDIUM,HIGH,CRITICAL"
          trivyignores: .trivyignore

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
          category: ${{ matrix.flavour }}-${{ matrix.arch }}

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8
        # v0.36.0
        if: ${{ inputs.submit_dependency_graph }}
        with:
          scan-type: "image"
          format: "github"
          output: "dependency-results-${{ matrix.flavour }}-${{ matrix.arch }}.sbom.json"
          image-ref: "trivy/${{ matrix.flavour }}-${{ matrix.arch }}:${{ github.sha }}"
          github-pat: ${{ secrets.GITHUB_TOKEN }}
