name: trivy
on:
  push:
    branches:
      - 3.5/edge
      - 3.4/edge
      - 4.0/edge
  pull_request:
  workflow_call:
    inputs:
      branch:
        type: string
        default: ""
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      branch: ${{ inputs.branch }}
  scan:
    name: Trivy scan and sbom generation
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour:
          - charmed-spark
          - charmed-spark-kyuubi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Install rockcraft (for skopeo)
        run: |
          sudo snap install rockcraft --classic --edge
      - name: Get Artifact Name
        id: artifact
        run: |
          FLAVOUR=${{ matrix.flavour }}
          BASE_ARTIFACT=$(make help | grep 'Artifact: ' | sed "s/charmed-spark/$FLAVOUR/g")
          echo "base_artifact_name=${BASE_ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: charmed-spark
          path: charmed-spark
      - name: Import locally
        run: |
          # Unpack artifact
          mv charmed-spark/${{ steps.artifact.outputs.base_artifact_name }} .
          sudo rockcraft.skopeo --insecure-policy copy \
            docker-archive:${{ steps.artifact.outputs.base_artifact_name }} \
            docker-daemon:trivy/${{ matrix.flavour }}:test
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: "trivy/${{ matrix.flavour }}:test"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "MEDIUM,HIGH,CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
          ref: ${{ inputs.branch }}
          category: ${{ matrix.flavour }}

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: "image"
          format: "spdx-json"
          output: "dependency-results-${{ matrix.flavour }}.sbom.json"
          image-ref: "trivy/${{ matrix.flavour }}:test"
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          severity: "MEDIUM,HIGH,CRITICAL"
          scanners: "vuln"

      - name: Upload trivy report as a Github artifact (${{ matrix.flavour }})
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report-${{ matrix.flavour }}
          path: "${{ github.workspace }}/dependency-results-${{ matrix.flavour }}.sbom.json"
          retention-days: 90
